/* generated by research-tools/charts.py — setup list baked in so it works from file:// */
window.TRADE_SETUPS={"generated":"2026-09-29T00:15:47+10:00","tickers":{"NTAP":{"state":"BELOW PIVOT","entry":209.16,"stop":192.9,"r2":241.68,"r3":257.94,"last":201.02,"rmult":-0.5,"chart":true},"HNGE":{"state":"BELOW PIVOT","entry":96.76,"stop":89.5,"r2":111.28,"r3":118.54,"last":92.95,"rmult":-0.52,"chart":true},"HALO":{"state":"BREAKOUT CONFIRMED","entry":111.25,"stop":105.4,"r2":122.95,"r3":128.8,"last":113.01,"rmult":0.3,"chart":true},"ASX":{"state":"BELOW PIVOT","entry":45.62,"stop":42.1,"r2":52.66,"r3":56.18,"last":43.19,"rmult":-0.69,"chart":true},"HPE":{"state":"BELOW PIVOT","entry":65.75,"stop":60.2,"r2":76.85,"r3":82.4,"last":61.36,"rmult":-0.79,"chart":true},"FTNT":{"state":"BELOW PIVOT","entry":181.47,"stop":166.0,"r2":212.41,"r3":227.88,"last":173.43,"rmult":-0.52,"chart":true},"KEYS":{"state":"BELOW PIVOT","entry":375.06,"stop":343.5,"r2":438.18,"r3":469.74,"last":357.14,"rmult":-0.57,"chart":true}}};
/* ===== TRADE CHARTS — dashboard linker + modal (research-tools/charts.py prepends window.TRADE_SETUPS) =====
   On load: finds every mention of a setup ticker (cards, tables, bubbles, tape, prose) and makes it open that
   ticker's arcade chart (charts/<T>.html) in a modal overlay. Existing links keep working; a small 🕹 button is
   added next to them instead. Ctrl/⌘/middle-click opens the chart page itself. Works from file:// (no fetch). */
(function(){
  'use strict';
  if(window.__TC_LINKER) return; window.__TC_LINKER=true;
  var SET=(window.TRADE_SETUPS||{}).tickers||{};
  var me=document.currentScript, src=(me&&me.src)||'';
  var BASE=src?src.replace(/_assets\/charts-link\.js(?:[?#].*)?$/,''):'charts/';
  var TK=Object.keys(SET).filter(function(t){return SET[t].chart;}).sort(function(a,b){return b.length-a.length;});
  if(!TK.length) return;
  var RM=window.matchMedia&&matchMedia('(prefers-reduced-motion: reduce)').matches;
  var RE=new RegExp('(^|[^A-Za-z0-9$/_.-])('+TK.map(function(t){return t.replace(/[.\-]/g,'\\$&');}).join('|')+')(?![A-Za-z0-9_-])','g');
  var SKIP='a,button,script,style,textarea,select,option,input,code,pre,svg,noscript,nav,title,.tc-modal,[data-no-chart],#banner,.tc-link,.tc-btn';
  var PRIMARY='.card .tk,td.tkc,.tkbig,.sig .tkb,.tkpanel h3,.detail h3';

  var css=document.createElement('style'); css.id='tc-link-style';
  css.textContent=
    '.tc-link{color:inherit;text-decoration:underline dotted 2px;text-underline-offset:3px;cursor:pointer;border-radius:4px}'+
    '.tc-link:hover,.tc-link:focus-visible{text-decoration-style:solid;color:#0a7cff;outline:none;background:rgba(0,229,255,.12)}'+
    '.tc-link.tc-pri{text-decoration:none;display:inline-flex;align-items:center;gap:.25em}'+
    '.tc-link.tc-pri:hover,.tc-link.tc-pri:focus-visible{color:inherit;background:none}'+
    '.tc-joy{display:inline-grid;place-items:center;font-style:normal;font-size:.5em;min-width:1.9em;height:1.9em;line-height:1;padding:0 .2em;border-radius:6px;'+
      'background:#0e0b2e;color:#00e5ff;border:2px solid #1d1b3a;box-shadow:0 0 0 1px #00e5ff inset,2px 2px 0 #1d1b3a;vertical-align:middle;letter-spacing:0;text-shadow:0 0 4px #00e5ff}'+
    '.tc-link:hover .tc-joy,.tc-link:focus-visible .tc-joy,.tc-btn:hover,.tc-btn:focus-visible{background:#00e5ff;color:#0e0b2e;text-shadow:none}'+
    '.tc-btn{display:inline-grid;place-items:center;margin-left:.3em;font-size:12px;width:24px;height:24px;border-radius:6px;text-decoration:none;vertical-align:middle;'+
      'background:#0e0b2e;color:#00e5ff;border:2px solid #1d1b3a;box-shadow:0 0 0 1px #00e5ff inset,2px 2px 0 #1d1b3a;cursor:pointer;line-height:1}'+
    '.tc-modal{position:fixed;inset:0;z-index:2147483000;display:flex;align-items:center;justify-content:center;background:rgba(7,6,26,.78);padding:2vh 2vw}'+
    '.tc-modal[hidden]{display:none}'+
    '.tc-box{position:relative;display:flex;flex-direction:column;width:min(1280px,96vw);height:min(900px,94vh);background:#07061a;border:3px solid #6b5cff;'+
      'box-shadow:0 0 0 3px #000,0 0 30px #6b5cffaa,0 0 60px #00e5ff44;animation:tc-pop .22s ease-out}'+
    '@keyframes tc-pop{from{transform:scale(.92);opacity:0}to{transform:none;opacity:1}}'+
    '.tc-bar{display:flex;align-items:center;gap:10px;padding:6px 8px 6px 12px;background:#0e0b2e;border-bottom:3px solid #6b5cff;color:#e8e6ff;font:700 14px/1.2 ui-monospace,Menlo,Consolas,monospace}'+
    '.tc-bar b{flex:1;letter-spacing:1px;color:#fff;text-shadow:0 0 6px #00e5ff}'+
    '.tc-bar a{color:#00e5ff;font-size:12px;text-decoration:none;border:2px solid #00e5ff;padding:5px 8px}'+
    '.tc-x{font:700 18px/1 ui-monospace,monospace;color:#fff;background:#ff2a2a;border:3px solid #000;box-shadow:0 0 10px #ff2a2a;min-width:44px;height:40px;cursor:pointer}'+
    '.tc-x:focus-visible{outline:3px solid #ffd700;outline-offset:2px}'+
    '.tc-box iframe{flex:1;width:100%;border:0;background:#07061a}'+
    'html.tc-lock,html.tc-lock body{overflow:hidden}'+
    '@media (max-width:760px){.tc-modal{padding:0}.tc-box{width:100vw;height:100vh;height:100dvh;border-width:0}.tc-bar{padding-top:max(6px,env(safe-area-inset-top))}.tc-bar a{display:none}}'+
    '@media (prefers-reduced-motion:reduce){.tc-box{animation:none}}';
  document.head.appendChild(css);

  function href(t){return BASE+encodeURIComponent(t)+'.html';}
  function tipOf(t){var s=SET[t]||{},bits=[s.state||'setup'];if(s.entry!=null)bits.push('entry $'+s.entry.toFixed(2));bits.push(s.stop!=null?'stop $'+s.stop.toFixed(2):'stop not set');return t+' trade chart: '+bits.join(' · ');}
  function mkLink(t,pri){var a=document.createElement('a');a.className='tc-link'+(pri?' tc-pri':'');a.href=href(t);a.setAttribute('data-tc',t);a.title=tipOf(t);
    a.appendChild(document.createTextNode(t));if(pri){var j=document.createElement('i');j.className='tc-joy';j.setAttribute('aria-hidden','true');j.textContent='🕹';a.appendChild(j);}return a;}
  function mkBtn(t){var b=document.createElement('a');b.className='tc-btn';b.href=href(t);b.setAttribute('data-tc',t);b.title=tipOf(t);b.setAttribute('aria-label','Open '+t+' trade chart');b.textContent='🕹';return b;}

  function link(root){
    // 1) anchors that are just a ticker (e.g. <a href="tickers/HALO.html"><b>HALO</b></a>): keep them, add a 🕹 button
    root.querySelectorAll('a').forEach(function(a){
      if(a.hasAttribute('data-tc')||a.getAttribute('data-tc-done')||a.closest('nav,.tc-modal,[data-no-chart]')) return;
      var t=(a.textContent||'').trim(); if(!SET[t]||!SET[t].chart) return;
      a.setAttribute('data-tc-done','1'); a.parentNode.insertBefore(mkBtn(t),a.nextSibling);
    });
    // 2) plain-text mentions
    var w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode:function(n){
      if(!n.nodeValue||n.nodeValue.length<2) return NodeFilter.FILTER_REJECT;
      var p=n.parentElement; if(!p||p.closest(SKIP)) return NodeFilter.FILTER_REJECT;
      RE.lastIndex=0; return RE.test(n.nodeValue)?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT;}});
    var nodes=[],n; while((n=w.nextNode())) nodes.push(n);
    nodes.forEach(function(node){
      var s=node.nodeValue,frag=document.createDocumentFragment(),i=0,m,pri=false,el=node.parentElement;
      try{pri=!!el.closest(PRIMARY)&&el.closest(PRIMARY).textContent.trim().indexOf(s.trim())===0;}catch(e){}
      RE.lastIndex=0;
      while((m=RE.exec(s))){var st=m.index+m[1].length;if(st>i)frag.appendChild(document.createTextNode(s.slice(i,st)));frag.appendChild(mkLink(m[2],pri&&st===s.length-s.replace(/^\s+/,'').length));i=st+m[2].length;}
      if(i<s.length) frag.appendChild(document.createTextNode(s.slice(i)));
      node.parentNode.replaceChild(frag,node);
    });
  }

  // ---- modal
  var modal=null,frame=null,title=null,full=null,opener=null;
  function build(){
    modal=document.createElement('div');modal.className='tc-modal';modal.hidden=true;modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.setAttribute('data-no-chart','');
    modal.innerHTML='<div class="tc-box"><div class="tc-bar"><b>🕹 TRADE CHART</b><a class="tc-full" target="_blank" rel="noopener">OPEN FULL PAGE ↗</a>'+
      '<button type="button" class="tc-x" aria-label="Close chart">✕</button></div><iframe title="Trade chart" loading="eager"></iframe></div>';
    document.body.appendChild(modal);
    frame=modal.querySelector('iframe');title=modal.querySelector('.tc-bar b');full=modal.querySelector('.tc-full');
    modal.querySelector('.tc-x').addEventListener('click',close);
    modal.addEventListener('click',function(e){if(e.target===modal)close();});
  }
  function open(t){
    if(!SET[t]) return;
    if(!modal) build();
    opener=document.activeElement;
    title.textContent='🕹 '+t+' · '+(SET[t].state||'SETUP')+' · TRADE CHART';
    modal.setAttribute('aria-label',t+' trade chart');
    full.href=href(t); frame.src=href(t)+'?embed=1';
    modal.hidden=false; document.documentElement.classList.add('tc-lock');
    modal.querySelector('.tc-x').focus({preventScroll:true});
    window.__TC_OPEN=t;
  }
  function close(){
    if(!modal||modal.hidden) return;
    modal.hidden=true; frame.src='about:blank'; document.documentElement.classList.remove('tc-lock'); window.__TC_OPEN=null;
    if(opener&&opener.focus) try{opener.focus({preventScroll:true});}catch(e){}
  }
  document.addEventListener('click',function(e){
    var a=e.target.closest&&e.target.closest('[data-tc]'); if(!a) return;
    if(e.defaultPrevented||e.button!==0||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey) return;
    e.preventDefault(); e.stopPropagation(); open(a.getAttribute('data-tc'));
  },true);
  document.addEventListener('keydown',function(e){if(e.key==='Escape') close();});
  window.TradeCharts={open:open,close:close,base:BASE,tickers:TK};

  function init(){
    link(document.body);
    var m=/[#&?]chart=([A-Z.\-]{1,8})/.exec(location.hash+location.search); if(m) open(m[1]);
  }
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',init); else init();
})();
